swagger: "2.0"

info:
  version: "1"
  title: ecommerce-backend

host: localhost:8080
basePath: /api/v1

schemes:
  - http

consumes:
  - application/json

securityDefinitions:
  Token:
    type: apiKey
    in: header
    name: x-backoffice-auth-token

security:
  - Token: []

paths:
  /auth/register:
    post:
      description: Register New User
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/registerRequestBody"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/defintions/userResponseBody"

  /auth/login:
    post:
      description: Login User
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/loginRequestBody"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/defintions/userResponseBody"

definitions:
  registerRequestBody:
    type: object
    properties:
      email:
        type: string
        example: "user@example.com"
      firstName:
        type: string
        example: "John"
      lastName:
        type: string
        example: "Doe"
      password:
        type: string
        example: "12345"

  loginRequestBody:
    type: object
    properties:
      email:
        type: string
        example: "user@example.com"
      password:
        type: string
        example: "12345"

  userResponseBody:
    type: object
    properties:
      email:
        type: string
        example: "user@example.com"
      firstName:
        type: string
        example: "John"
      lastName:
        type: string
        example: "Doe"
      role:
        type: number
        example: 0
      purchases:
        type: array
